"""empty message

Revision ID: c468aa991d63
Revises: 4d06d403b39a
Create Date: 2019-10-19 15:00:01.847127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c468aa991d63'
down_revision = '4d06d403b39a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('photo_id'),
    sa.UniqueConstraint('photo_id'),
    sa.UniqueConstraint('photo_path')
    )
    op.drop_table('photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('photo_id', sa.INTEGER(), nullable=False),
    sa.Column('photo_path', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('photo_id'),
    sa.UniqueConstraint('photo_id'),
    sa.UniqueConstraint('photo_path')
    )
    op.drop_table('photos')
    ### end Alembic commands ###
